---
- name: Waddle Bot Twitch Authenticator
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build
      tags:
        - build
      include_tasks:
        file: "jobs/build/build.yml"
        apply:
          tags: build
    - name: Run And Configure
      include_tasks:
        file: jobs/run/run.yml
    - name: Run tests to make sure app is running as expected
      include_tasks:
        file: jobs/tests/test.yml
